import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(00021500-0000-0000-C000-000000000046),
		helpstring("IQueryInfo Interface"),
		pointer_default(ptr)
	]
	interface IQueryInfo : IUnknown
	{
	typedef unsigned long DWORD;
        HRESULT GetInfoFlags ([out,retval] DWORD * pdwFlags);
        HRESULT GetInfoTip([in] DWORD dwFlags , [out,retval] wchar_t ** ppwszTip);
	};
[
	uuid(41059C57-975F-4B36-8FF3-C5117426647A),
	version(1.0),
	helpstring("Shell Extentsion 1.0 Type Library")
]
library SHEXlib
{
	//importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	//importlib("msado15.dll");

	[
		uuid(E19C0A68-F61C-450B-A974-A7BA6957829C),
		helpstring("SHEX Class")
	]
	coclass SHEX
	{
		[default] interface IQueryInfo;
	};
};
